version: '3.8'

services:
  cobalt:
    image: cobalt:latest
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "49000:9000"
    working_dir: /app
    command: ["node", "src/cobalt"]
    volumes:
      - ./:/app
