version: '3'
services:
  cobalt:
    build:
      context: .
      dockerfile: Dockerfile
    image: cobalt:latest
    container_name: cobalt
    restart: unless-stopped
    ports:
      - "49000:9000"
    volumes:
      - ./:/app
    environment:
      - NODE_ENV=production
